### ISSUE TITLE
Crash on startup in SSP

### ISSUE THREAD

**Issue by TheWolfJack** [TeamMD5/Reliquia#4]
SSP crashes on attempting to load a saved world.
Didn't test new world if the crash persists but can if requested.

Description: Unexpected error
java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.getSkyColorBody(World.java:1477)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:415)
	at net.minecraft.world.World.func_72833_a(World.java:1468)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1691)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1243)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full crash report attached
[crash-2016-12-26_01.06.03-client.txt](https://github.com/TeamMD5/Reliquia/files/672608/crash-2016-12-26_01.06.03-client.txt)

**Comment by KitsuneAlex** [comment]
thanks for the report, i already found out the issue, it has something to do with Forestry and im still trying to figure out what. For the moment just disabling the Forestry integration in the config should work
