### ISSUE TITLE
Crash Report (java.lang.NoClassDefFoundError: keri/reliquia/client/render/IBlockRenderingHandler)

### ISSUE THREAD

**Issue by Lightone** [TeamMD5/Reliquia#7]
try lunch the game and few seconds to load data of all mods, the game crashed

Crash log 

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: keri/reliquia/client/render/IBlockRenderingHandler
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:576)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: keri/reliquia/client/render/IBlockRenderingHandler

Crash Log [pastebin](http://pastebin.com/hR7ahepW)
<details>
  <summary>Full Crash Log</summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.2.8.4.jar)
  CamPatchingLoader (CMDCam v1.1.2 mc1.10.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 16/01/17 10:51 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: keri/reliquia/client/render/IBlockRenderingHandler
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:576)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: keri/reliquia/client/render/IBlockRenderingHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:71)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)
	... 10 more
Caused by: java.lang.ClassNotFoundException: keri.reliquia.client.render.IBlockRenderingHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/texture/TextureUtils$IIconRegister
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more
Caused by: java.lang.ClassNotFoundException: codechicken.lib.texture.TextureUtils$IIconRegister
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 140136992 bytes (133 MB) / 385531904 bytes (367 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 Optifine OptiFine_1.10.2_HD_U_D4 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
	UC	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
	UC	cmdcam{0.2} [CMDCam] (minecraft.jar) 
	UC	ivtoolkit{1.2.8.4} [IvToolkit] (minecraft.jar) 
	UC	BetterAchievements{0.3.0.30} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.30.jar) 
	UC	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UC	excore{1.6.1} [EXCore] (Excore-1.6.1-1.10.2(1).jar) 
	UC	JEI{3.12.1.287} [Just Enough Items] (jei_1.10.2-3.12.1.287.jar) 
	UC	FEI{1.0.15} [Forever Enough Items] (ForeverEnoughItems-1.0.15-1.10.2.jar) 
	UC	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UC	jeresources{0.5.3.65} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.3.65.jar) 
	UC	mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
	UC	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UC	reccomplex{1.2.1} [Recurrent Complex] (RecurrentComplex-1.2.1.jar) 
	UE	reliquia{0.0.7} [Reliquia] (Reliquia-[1.10.2]-0.0.7.jar) 
	UC	shadowmc{3.4.8} [ShadowMC] (ShadowMC-1.10.2-3.4.8.jar) 
	UC	shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
	UC	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UC	thutcore{3.2.3} [ThutCore] (thutcore-1.9.4-3.2.3.jar) 
	UC	thuttech{3.0.9} [Thut's Tech] (thuttech-3.0.9.jar) 
	UC	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (torohealth-1.10.2-1.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UC	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	UC	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.2.8.4.jar)
  
CamPatchingLoader (CMDCam v1.1.2 mc1.10.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3304' Renderer: 'Intel(R) HD Graphics 4000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)
</details>

**Comment by KitsuneAlex** [comment]
you need CodeChickenLib, you can either download it from CurseForge or chicken_bones' homepage
